title: Solarcel and Co.
email: info@solarcel.co.za
description: >- # this means to ignore newlines until "baseurl:"
  Comprehensive energy solutions for residential, commercial, and government sectors in South Africa and Zambia.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://solarcelandco.africa' # the base hostname & protocol for your site
github_username: solarcelandco

theme: minima

# Build settings
markdown: kramdown
